### ISSUE TITLE
Add our SPLC publications

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/BibTags#110]
- [x] https://dl.acm.org/doi/10.1145/3646548.3672589
- [x] https://dl.acm.org/doi/10.1145/3646548.3672590
- [x] https://dl.acm.org/doi/10.1145/3646548.3676540
- [x] https://dl.acm.org/doi/10.1145/3646548.3672598
- [x] https://dl.acm.org/doi/10.1145/3646548.3672593
- [x] https://dl.acm.org/doi/10.1145/3646548.3676602
- [x] https://dl.acm.org/doi/10.1145/3646548.3676550

Anything missing?

What about editorials (e.g., Re:Volution)?

**Comment by pmbittner** [comment]
I am adding the rest now.
